services:
  - type: web
    name: plant-detection-flask
    env: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SESSION_SECRET
        sync: false