services:
  - type: web
    name: plant-disease-detector
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools
      pip install --upgrade --force-reinstall setuptools
      pip cache purge
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: 3.10
